Staging
Revature-Cinephiliacs/UserRepo pull request #38
Opened 2021-04-26 17:02 UTC by clcheatle

2021-04-26 18:24 UTC, nicholasvvong approved these changes
Added follow functionality. Removed followingmovies related things from this service (meant to be in movie service)

2021-04-26 21:41 UTC, markmoorerev commented on Logic/UserLogic.cs
> +            newFollow.FolloweeUserId = followeeid;
duplicate?

2021-04-26 21:43 UTC, markmoorerev requested changes
correct that one duplicate line.

2021-04-27 14:02 UTC, nicholasvvong commented on Logic/UserLogic.cs
> +            newFollow.FolloweeUserId = followeeid;
one is follower, one is followee

2021-04-28 01:23 UTC, markmoorerev approved these changes

2021-04-28 01:23 UTC, merged